# This is a basic workflow to help you get started with Actions

name: 'Deploy'

# Controls when the action will run. 
on:
  # Triggers the workflow on push  request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.15.0
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_GITHUB_AZ_SUB: ${{ secrets.TF_VAR_GITHUB_AZ_SUB }}
          
      - name: Terraform validate
        run: terraform validate

     
      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_GITHUB_AZ_SUB: ${{ secrets.TF_VAR_GITHUB_AZ_SUB }}
          
    

